### PR TITLE
Add 'Special Inverted' to sliding doors

### PR DESCRIPTION
**Pull request by SFort**
You can do this with iron doors by facing them in a diffrent direction, which isn't viable for folding/sliding doors.

### CODE REVIEW

**Comment by techno-sam** [comment]
looks good! Could you make a custom icon for the special-inverted state?

**Comment by SFort** [comment]
The pull changes the icon to be the same one as "special" with the arrow pointing the other way. (i don't have any good ideas for a diffrent icon otherwise)

**Comment by techno-sam** [comment]
Oh, I must have missed that when I looked at the texture. I'll check with the team for any objections, then merge

**Review by IThundxr — APPROVED** [review]
Looks good to me!

**Pull request merged**
