### PR TITLE
de_de

### PR DESCRIPTION
**Pull request by TripleT-seb**
My German isn't perfect (my English isn't great either). Correction/review of the translation is needed. I hope my work is adequate. Thanks

### CODE REVIEW

**Review by realRobotix — CHANGES_REQUESTED** [review]
- [x] "entity.railways.conductor":
  A "Schaffner" is more of a "ticket inspector" than a "conductor". "Zugführer" is more applicable.
- [x] "entity.railways.benchcart" & "entity.railways.jukeboxcart":
  "Werkbanklore" and "Plattenspielerlore" are inline with the vanilla translations for the other minecarts -> no alternatives needed
- [x] "railways.ponder.conductor_redstoning.header":
  "Redstone Fernsteuerung mit Schaffnern" fits best -> no alternatives needed
- [x] "\u00fc unicode or ü?":
  Both work but "ü" is easier to read in code.

**Comment by TripleT-seb** [comment]
Thank you @realRobotix for your feedback.
You are right: "Zugführer" is a better translation than "Schaffner".
I will edit the other translations to fit.
Do you have an alternate suggestion for "Schaffnermütze"? (Eisenbahnermütze, Schirmmütze, Zugführermütze?)
Any other errors?

**Comment by realRobotix** [comment]
"Eisenbahnermütze" seems to fit best.
The rest looks good.

**Comment by TripleT-seb** [comment]
OK, I will make the relevant changes.
Thanks for your help.

**Review by realRobotix — APPROVED** [review]
looks great, can be merged now

**Comment by TripleT-seb** [comment]
One more thing: did I understand "create.railways.semaphore.search_mode" correctly?

**Comment by TechnoCatza** [comment]
Hello there, thought i look into here cause im german, to see if i can Help. Well from the Conversation in here, i can only see one thing we germans would say different, and thats _**Formsignal**_ . We would more likely say "Signalmast" Everything else looks fine to me.

**Comment by TripleT-seb** [comment]
Hello @TechnoCatza, thanks for your input.
I still prefer "Formsignal" over "Signalmast" though.
It helps with the differentiation between mechanical “Form-” and light “Licht-” signals.
Check the definition in the Eisenbahn-Signalordnung 1959 (ESO 1959):

(11) Die Signale sind entweder **Formsignale** und zeigen ein oder zwei Flügel als Tageszeichen und ebenso viele Lichter als Nachtzeichen, oder sie sind **Lichtsignale** mit ein oder zwei Lichtern als Tages- und Nachtzeichen.

[https://www.gesetze-im-internet.de/eso_1959/----.html](url)

**Comment by techno-sam** [comment]
Copying this over from discord (Erdbeere suggested this):
```
line 76-78     "railways.ponder.conductor_redstoning.text_1": "Schaffner können Knöpfe drücken, wenn Spieler die angucken.",
    "railways.ponder.conductor_redstoning.text_2": "Schaffner schalten auch Hebel um, wenn Spieler die angucken.",
    "railways.ponder.conductor_redstoning.text_3": "Schaffner aktivieren keinen Redstone, falls Spieler andersfarbige Schaffnermützen aufhaben als die."

better version:
"railways.ponder.conductor_redstoning.text_1": "Schaffner können Knöpfe drücken, wenn Spieler sie angucken.",
    "railways.ponder.conductor_redstoning.text_2": "Schaffner schalten auch Hebel um, wenn Spieler sie angucken.",
    "railways.ponder.conductor_redstoning.text_3": "Schaffner aktivieren kein Redstone, falls Spieler andersfarbige Schaffnermützen aufhaben als sie." ```

**Comment by TripleT-seb** [comment]
Hello @techno-sam, I have made the changes. 
This file should be ready for merging. Any other mistakes can be corrected in later updates. 
Thanks a lot.

**Review by techno-sam — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
