### PR TITLE
rewrite ci

### PR DESCRIPTION
**Pull request by realRobotix**
- [x] replace deprecated actions
- [x] replace deprecated discord notification 
  - [x] ~~use GitHub webhook instead ( repo > settings > webhooks > add webhook > individual events > workflow runs)~~
  - [x] fork, update and maybe maintain
- [x] use GitHub Actions Caches
- [x] upload compiled jars as artifacts to GitHub
- [x] deobf.jar should perhaps not be published

### CODE REVIEW

**Review by techno-sam — CHANGES_REQUESTED** [review]
This looks great so far! One issue though: could you re-implement sending a list of commits to discord when publishing a build? Send me your discord name, and I'll add you to the #previews channel so you can see what it looked like in the past. (I'll also include a screenshot)
Screenshot from 2022-12-03 07-32-19

**Review by techno-sam — COMMENTED** [review]
Didn't know about `[ci skip]`, thanks!

**Comment by realRobotix** [comment]
> Didn't know about `[ci skip]`, thanks!

there are also some different ways of skipping CI: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

**Review by techno-sam — APPROVED** [review]
Thank you, your contributor role is coming soon!

**Pull request merged**
