### PR TITLE
pl_pl

### PR DESCRIPTION
**Pull request by p1c14sty**
Polish translation of the mod

### CODE REVIEW

**Comment by p1c14sty** [comment]
dont know if ive put it to right folder so feel free to put it wherever you want

**Comment by p1c14sty** [comment]
oh yea ive copied translated file to wrong folder, sorry guys :/

**Comment by p1c14sty** [comment]
should be fine for now

**Review by techno-sam — APPROVED** [review]
Looks good, thank you!
LMK your discord, to get notified in the future about translations needed

**Comment by p1c14sty** [comment]
@techno-sam im πcia#0001 on discord :)

**Pull request merged**
